trapper/apps/media_classification/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from trapper.apps.media_classification import views


urlpatterns = patterns('',
	# Home page of animal observation app
	url(r'^$', TemplateView.as_view(template_name='media_classification/index.html'), name='index'),

	# Display project list and the details about given project
	url(r'project/list/$', views.ProjectListView.as_view(), name='project_list'),
	url(r'project/detail/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
        url(r'project/update/(?P<pk>\d+)/$', views.ProjectUpdateView.as_view(), name='project_update'),
	url(r'project/create/(?P<rp_pk>\d+)/$', views.ProjectCreateView.as_view(), name='project_create'),

	# Attributeset views
	url(r'attributeset/detail/(?P<pk>\d+)/$', views.AttributeSetDetailView.as_view(), name='attributeset_detail'),
	url(r'attributeset/list/$', views.AttributeSetListView.as_view(), name='attributeset_list'),

        url(r'attributeset/create/$', views.AttributeSetCreateView.as_view(), name='attributeset_create'),
        url(r'attributeset/update/(?P<pk>\d+)/$', views.AttributeSetUpdateView.as_view(), name='attributeset_update'),
	#url(r'attributeset/delete/(?P<pk>\d+)/$', views.AttributeSetDeleteView, name='attributeset_delete'),

	# Sequence views
	url(r'sequence/detail/(?P<sequence_pk>\d+)/$', views.SequenceDetailAjaxView.as_view(), name='sequence_detail'),
	url(r'sequence/list/(?P<collection_pk>\d+)/$', views.SequenceListAjaxView.as_view(), name='sequence_list'),
	url(r'sequence/create/(?P<collection_pk>\d+)/$', views.SequenceCreateUpdateAjaxView.as_view(), name='sequence_create'),
	url(r'sequence/update/(?P<sequence_pk>\d+)/$', views.SequenceCreateUpdateAjaxView.as_view(), name='sequence_update'),
	url(r'sequence/delete/(?P<sequence_pk>\d+)/$', views.SequenceDeleteAjaxView.as_view(), name='sequence_delete'),

	# Display the classification form and process (action) it
	url(r'classify/(?P<project_id>\d+)/(?P<resource_id>\d+)/(?P<collection_id>\d+)/$', views.classify_resource, name='classify'),
	url(r'classify/(?P<project_id>\d+)/(?P<resource_id>\d+)/(?P<collection_id>\d+)/(?P<user_id>\d+)/$', views.classify_resource, name='classify_user'),
	#url(r'classify/action/$', views.process_classify, name='classify_action'),

	# Displays the details about given classification
	url(r'classification/detail/(?P<pk>\d+)/$', views.ClassificationDetailView.as_view(), name='classification_detail'),
 	url(r'classification/list/(?P<pk>\d+)/$', views.ClassificationListView.as_view(), name='classification_list'),
 	url(r'classification/delete/(?P<pk>\d+)/$', views.ClassificationDeleteView.as_view(), name='classification_delete'),

	#url(r'crowd/list/$', views.cs_resource_list, name='cs_resource_list'),
)

trapper/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
                # Trapper homepage
                url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
                url(r'^msg/$', TemplateView.as_view(template_name='base.html'), name='msg'),
                # Media classification urls
                url(r'^media_classification/', include('trapper.apps.media_classification.urls', namespace='media_classification')),
                # Research urls
                url(r'^research/', include('trapper.apps.research.urls', namespace='research')),
                # Storage urls
                url(r'^storage/', include('trapper.apps.storage.urls', namespace='storage')),
                # Messaging urls
                url(r'^messaging/', include('trapper.apps.messaging.urls', namespace='messaging')),
                # Accounts urls
                url('', include('django.contrib.auth.urls')),
                url(r'^accounts/', include('trapper.apps.accounts.urls', namespace='accounts')),
                # GeoMap urls
                url(r'^geomap/', include('trapper.apps.geomap.urls', namespace='geomap')),
                # Comments
                url(r'^comments/', include('fluent_comments.urls')),
                url(r'^tinymce/', include('tinymce.urls')),
                url(r'^grappelli/', include('grappelli.urls')),
                url(r'^admin/', include(admin.site.urls)),
                url(r'^admin_gis/', include(admin_gis.site.urls)),
                url(r'', include('leaflet_storage.urls')),
                url(r"^select2/", include("django_select2.urls")),
               )

if settings.DEBUG:
        urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        '''
	urlpatterns = patterns('',
                url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),
                url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
	) + urlpatterns
        '''

trapper/apps/media_classification/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django import forms
from django.conf import settings
from django.db.models import get_model

from trapper.apps.storage.models import Resource
from trapper.apps.research.models import Project as RProject, ProjectCollection as RProjectCollection
from django_select2.fields import AutoModelSelect2Field

from django_hstore import hstore

import json
from operator import itemgetter
from collections import OrderedDict


class Project(models.Model):
    """Describes a single classification project existing withing the system
    """

    name = models.CharField(max_length=255)
    research_project = models.ForeignKey(RProject, related_name='classification_projects')
    collections = models.ManyToManyField(RProjectCollection, through='ProjectCollection', blank=True, null=True, related_name="classifications")
    """Collections assigned to the project"""
    createdby = models.ForeignKey(User, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, default='2014-01-01 12:00:00')
    sequencing_enabled = models.BooleanField("Sequences", default=True, help_text="Enable sequencing interface")
    cs_enabled = models.BooleanField(default=True)
    """Is crowd-sourcing enabled for the project ?"""

    def __unicode__(self):
        return unicode(self.name)

    def get_all_cs_resources(self):
        """Returns a list of crowd-sourcing enabled resources for given project."""

        resources = []

        if not self.cs_enabled:
            return resources

        for c in self.projectcollection_set.filter(cs_enabled=True):
            new = [r for r in c.collection.resources.all()]
            resources.extend(new)
        return list(set(resources))

    def is_project_admin(self, user):
        role = self.cproject_roles.filter(user=user)
        return len(role) > 0 and role[0].name == 'A'

    # TODO: given user can have only one role in a project; rewrite tests below
    def determine_roles(self, user):
        """Returns a tuple of project roles for given user.

        :param user: user for which the roles are determined
        :type user: :py:class:`django.contrib.auth.models.User`
        :return: list of role names of given user withing the project
        :rtype: str
        """

        return [r.name for r in self.cproject_roles.filter(user=user)]

    def can_update(self, user):
        """Determines whether given user can update the project.

        :param user: user for which the test is made
        :type user: :py:class:`django.contrib.auth.models.User`
        :return: True if user can edit the project, False otherwise
        :rtype: bool
        """

        return self.cproject_roles.filter(user=user, name__in=ProjectRole.ROLE_EDIT).count() > 0

    def can_detail(self, user):
        """Determines whether given user can see the details of a project.

        :param user: user for which the check is made
        :type user: :py:class:`django.contrib.auth.models.User`
        :return: True if user can see the details of the project, False otherwise
        :rtype: bool
        """

        return self.cproject_roles.filter(user=user).count() > 0

    def get_absolute_url(self):
        return reverse('media_classification:project_detail', kwargs={'pk':self.pk})


class ProjectCollection(models.Model):
    """Many-To-Many model for Project-Collection relationship."""

    project = models.ForeignKey(Project)
    collection = models.ForeignKey(RProjectCollection)
    active = models.BooleanField("Active", default=True)
    """Is collection "active" within the project at given moment ?"""
    group_by_location = models.BooleanField("Group resources by location", default=False)
    """Should resources for this collection be grouped by location in classification view?"""
    sequencing_experts = models.BooleanField("Sequences editable by experts", default=True, help_text="Allow experts to create and edit sequences")
    cs_enabled = models.BooleanField("Crowd-Sourcing", default=True, help_text="Enable Crowd-Sourcing")
    """Is collection available for the crowd-sourcing ?"""

    def __unicode__(self):
        return unicode("%s" % self.collection)

    def get_resources(self):
        return self.collection.collection.resources.all().order_by('date_recorded', 'name')

    def get_resources_with_status(self):
        resources = self.get_resources()
        resources_pks = resources.values_list('pk', flat=True)
        status_list = Classification.objects.filter(
            project__pk=1, resource__pk__in=resources_pks
        ).values_list('approved', flat=True).order_by('resource__date_recorded', 'resource__name')
        return zip(resources, status_list)

#---------------------------------------------------------------#


class AttributeSet(models.Model):
    """Defined group of attributes describing given classification form.
    Such set is defined per-resource type, and is defined in given classification project.
    """

    CUSTOM_ATTRS_FIELDS = {
        'B': forms.BooleanField,
        'F': forms.FloatField,
        'I': forms.IntegerField,
        'S': forms.CharField,
    }

    name = models.CharField(max_length=255)
    project = models.OneToOneField(Project, verbose_name='Media classification project', null=True, blank=True, related_name="attributeset")
    predefined_attrs = hstore.DictionaryField(null=True, blank=True)
    custom_attrs = hstore.DictionaryField(null=True, blank=True)
    dynamic_attrs_order = models.TextField(null=True, blank=True)
    static_attrs_order = models.TextField(null=True, blank=True)
    owner = models.ForeignKey(User, null=True, blank=True, related_name='owned_attsets')

    objects = hstore.HStoreManager()

    def __unicode__(self):
        return unicode("Name: %s | Project: %s" % (self.name, self.project.name))

    def get_absolute_url(self):
        return reverse('media_classification:attributeset_detail', kwargs={'pk':self.pk})

    def can_edit(self, user):
        return self.owner == user

    def get_pre_attrs_names(self):
        return settings.PREDEFINED_ATTRIBUTES_SIMPLE.keys() + settings.PREDEFINED_ATTRIBUTES_MODELS.keys()

    def get_active_pre_attrs_names(self):
        config = self.get_pre_attrs_names()
        active = []
        for attr in config:
            if self.predefined_attrs[attr] == 'true':
                active.append(attr)
        return active

    def get_all_attrs_names(self):
        all = [[],[]] # [[dynamic_form], [static_form]]
        for at in self.get_active_pre_attrs_names():
            if self.predefined_attrs['target_%s' % at] == 'D':
                all[0].append(at)
            else:
                all[1].append(at)
        for at in self.custom_attrs.keys():
            if json.loads(self.custom_attrs[at])['target'] == 'D':
                all[0].append(at)
            else:
                all[1].append(at)
        return all

    def get_dynamic_attrs_order(self):
        try:
            return self.dynamic_attrs_order.split(',')
        except:
            return []

    def get_static_attrs_order(self):
        try:
            return self.static_attrs_order.split(',')
        except:
            return []

    def update_attrs_order(self):
        all_attrs_names = self.get_all_attrs_names()
        dynamic_attrs_order = self.get_dynamic_attrs_order()
        static_attrs_order = self.get_static_attrs_order()
        ordered_attrs = []
        new_attrs = []
        for at in all_attrs_names[0]: # dynamic_form
            if not at in dynamic_attrs_order:
                dynamic_attrs_order.append(at)
        for at in dynamic_attrs_order:
            if not at in all_attrs_names[0]:
                del dynamic_attrs_order[dynamic_attrs_order.index(at)]
        for at in all_attrs_names[1]: # static_form
            if not at in static_attrs_order:
                static_attrs_order.append(at)
        for at in static_attrs_order:
            if not at in all_attrs_names[1]:
                del static_attrs_order[static_attrs_order.index(at)]
        self.dynamic_attrs_order = ','.join(dynamic_attrs_order)
        self.static_attrs_order = ','.join(static_attrs_order)
        self.save()

    def parse_hstore_values(self, field, attr=None):
        parsed_values = {}
        # if attr not specified parse all
        if not attr:
            items = getattr(self, field).items()
        else:
            items = [(attr, getattr(self, field)[attr], ),]
        for k,v in items:
            try:
                parsed_values[k] = json.loads(v)
            except ValueError:
                # if it is not a json it must be a simple string so just add it to a parsed_values dict
                parsed_values[k] = v
        return parsed_values

    def prepare_class_form_fields_defs(self):
        # parsed custom attributes
        ca = self.parse_hstore_values('custom_attrs')
        # parsed predefined attributes
        pa = self.parse_hstore_values('predefined_attrs')
        form_fields = OrderedDict()
        form_fields['D'] = OrderedDict() # "D" -> dynamic form
        form_fields['S'] = OrderedDict() # "S" -> dynamic form
        # first prepare predefined attributes:
        pas = settings.PREDEFINED_ATTRIBUTES_SIMPLE
        pam = settings.PREDEFINED_ATTRIBUTES_MODELS
        for key in pas.keys():
            if pa.get(key):
                if pas[key].get('widget'):
                    widget = pas[key]['widget']
                    formfield = pas[key]['formfield'](required=pa['required_%s' % key] ,widget=widget)
                else:
                    formfield = pas[key]['formfield'](required=pa['required_%s' % key])
                form_fields[pa['target_%s' % key]][key] = formfield
        for key in pam.keys():
            if pa.get(key):
                model = get_model(pam[key]['app'], key)

trapper/apps/media_classification/templates/media_classification/attributeset_list.html
{% extends "media_classification/base.html" %}
{% load staticfiles %}
{% block content %}
{% if attributesets %}
	<table class="table">
	<th>Name</th>
	<th>Resource type</th>
	<th>Detail</th>
	<th>Update</th>
	{% for attributeset in attributesets %}
	<tr>
		<td>{{attributeset.name}}</td>
		<td>{{attributeset.resource_type}}</td>
		<td><a href="{% url "media_classification:attributeset_detail" attributeset.pk %}"><span class="glyphicon glyphicon-search"></span></a></td>
		<td><a href="{% url "media_classification:attributeset_update" attributeset.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
	</tr>
	{% endfor %}
	</table>
{% else %}
No project available. Start one now!
{% endif %}

{% endblock content %}

trapper/apps/media_classification/templates/media_classification/classification_confirm_delete.html
{% extends "media_classification/base.html" %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
<p>Are you sure you want to delete "{{object}}" ? </p>
<br />
<input type="submit" name="submit" value="Confirm"/>
</form>
{% endblock content %}

trapper/apps/media_classification/templates/media_classification/classification_detail.html
{% extends "media_classification/base.html" %}

{% block content %}
{% include "media_classification/classification_display.html" %}
{% endblock content %}

trapper/apps/media_classification/templates/media_classification/classification_display.html
{% load thumbnail %}

<input class="action-select" name="action-select" value="{{ classification.id }}" type="checkbox" form="id_action_posts"/>

<div class="row">


<div class="col-md-2">

  <div class="thumbnail">
    <img src="{{ classification.resource.file|thumbnail_url:'carousel' }}"/>
    <div class="">
      <p class="{{ classification.resource.get_icon_class }}"><strong>{{ classification.resource.name }}</strong>
	{% if classification.approved %}
	   <i class="icon-check icon-2x pull-right", style="color:darkolivegreen"></i>
	{% endif %}
	<br><small>{{ classification.resource.date_recorded }}</small>
      </p>
    </div>
  </div>
</div>

<div class="col-md-10">

<div class="panel panel-default">
  <div class="panel-heading">
    Resource: {{ classification.resource.name }} <a href="{{ classification.resource.get_absolute_url }}"><span class="glyphicon glyphicon-search"></span></a>
    , Approved: {{ classification.approved }}
    , Approved by: {{ classification.approved_by }}
    , Project: {{ classification.project.name }}
    , ProjectColection: {{ classification.pcollection }}
    , Location: {{ classification.resource.location }}
  </div>
  {{ classification.data_static_form }}<br>
  {% for row in classification.data_dynamic_form_rows.all %}
     {{ row.data_dynamic_form_row }}<br>
  {% endfor %}
</div>

<p>
  <a href="{% url 'media_classification:classify' project.pk classification.resource.pk classification.pcollection.pk %}" class="btn btn-success btn-xs" role="button">View</a>
  <a href="{% url 'media_classification:classification_delete' classification.pk %}" class="btn btn-danger btn-xs" role="button">Delete</a>
</p>

</div>
</div>

trapper/apps/media_classification/templates/media_classification/classification_list.html
{% extends "media_classification/base.html" %}
{% load crispy_forms_tags %}
{% load bootstrap_pagination %}
{% load staticfiles %}

{% block header %}
<script type="text/javascript" src="{% static "js/select2.js" %}"></script>
<link type="text/css" href="{% static "css/select2.css" %}" media="screen" rel="stylesheet">

<script type="text/javascript">
    $(function () {
	$('select.selectmultiple').select2({
	    width: 150,
	    minimumInputLength: 3,
	});
    });
</script>
{% endblock header %}



{% block content %}

{% if is_paginated %}
   {% bootstrap_paginate page_obj %}
{% endif %}

<form class="form-inline" action="">
{% crispy filtering_form %}
<button type="submit" class="btn btn-default">Apply</button>
<a class="small" href="{% url "media_classification:classification_list" project.id %}">Clear all filters</a>
<span class="pull-right">{{ qs_filtered_len }} ({{ qs_all_len }})</span>
</form>
<br>
<form action="" method="post" id="id_action_posts" class="form-inline">
{% csrf_token %}
{% include 'actions_select.html' %}<br>
{% for classification in page_obj %}
   {% include "media_classification/classification_display.html" %}
{% endfor %}
</form>

{% endblock content %}

trapper/apps/media_classification/templates/media_classification/classification_results2.html
<div style="font-size:12px">
  <p>
    Admin: {{ user_is_admin}} <br>
    {{ classification.pk }}
    Approved <strong> {{ classification.approved }} </strong> <br>
    Approved by <strong> {{ classification.approved_by }} </strong>on <strong> {{ classification.approved_date }} </strong><br>
    {{ classification.approved_data_static_form }} <br>
    {{ classification.approved_data_dynamic_form_rows.values }} <br>
  </p>
  <div class="panel-group" id="results">
    {% for uc in classification.users_classifications.all %}
    <div class="panel panel-success">
      <div class="panel-heading">
	    <strong> 
	      <i class="icon-user"></i> <a href="{{uc.user.userprofile.get_absolute_url}}">{{uc.user.get_full_name}}</a>
	      {{ uc.get_user_role.get_name_display|lower }}  
	    </strong>
	    on {{ uc.modified }}
          <a class="pull-right" data-toggle="collapse" data-parent="#results" href="#uc_{{uc.pk}}">Show / Hide</a>
      </div>
      <div id="uc_{{uc.pk}}" class="panel-collapse collapse">
	<div class="panel-body">
	  
	  {% if static_class_form %}
	  <div class="" style="overflow-x: auto">
	    <table class="table table-striped table-condensed">
	      <thead>
		<tr>
		  {% for key in uc.classification.get_attset.get_static_attrs_order %}
		  <th>{{ key|lower|capfirst }}</th>
		  {% endfor %}
		</tr>
	      </thead>
	      <tbody>
		<tr>
		  {% for val in uc.get_static_values %}
		  <td>{{ val }}</td>
		  {% endfor %}
		</tr>
	      </tbody>
	    </table>
	  </div>
	  {% endif %}

	  {% if dynamic_class_form %}
	  <div class="" style="overflow-x: auto">
	    <table class="table table-striped table-condensed">
	      <thead>
		<tr>
		  {% for key in uc.classification.get_attset.get_dynamic_attrs_order %}
		  <th>{{ key|lower|capfirst }}</th>
		  {% endfor %}
		</tr>
	      </thead>
	      <tbody>
		{% for row in uc.get_dynamic_rows %}
		<tr>
		  {% for val in row %}
		  <td>{{ val }}</td>
		  {% endfor %}
		</tr>
		{% endfor %}
	      </tbody>
	    </table>
	  </div>
	  {% endif %}

	  <br><a href="{% url "media_classification:classify_verify" project.id resource.id collection.id uc.user.id %}" class="btn btn-warning btn-xs">Open</a>
	</div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

trapper/apps/media_classification/templates/media_classification/classify_resource_carousel.html
{% load thumbnail %}

<div id="collapseOne" class="panel-collapse collapse in">
  <div class="panel-body row" style="padding:0 0 40px 0">

    <div class="jcarousel-wrapper col-md-10">
    <div class="jcarousel">
      <ul id="selectable">
	{% for r, approved_status in resources %}
	{% thumbnail r.file "carousel" as thumb %}
        <li {% if r == resource %} class="scroll_to_current" {% endif %} id="{{ r.pk }}">
	  <div class="thumbnail-condensed" style="margin-down:0px;">
	  <a href="#" class="thumbnail-condensed {% if r == resource %} current_resource {% endif %}">
	    <img width="{{ thumb.width }}" height="{{ thumb.height }}" src="{{ thumb.url }}"></img>
	  </a>

	  <div class="">
            <p class="{{ r.get_icon_class }}"><strong>{{ r.name }}</strong>
	      {% if approved_status %}
	        <i class="icon-check icon-2x pull-right", style="color:darkolivegreen"></i>
	      {% endif %}
	      <br>{{ r.date_recorded }}
	    </p>
            <p><a href="{% url 'media_classification:classify' project.pk r.pk collection.pk %}" class="btn btn-primary btn-xs" role="button">Classify</a> <a href="#" class="btn btn-default btn-xs" role="button">Update</a></p>
	  </div>
	  </div>
	  {% if user_is_admin or collection.sequencing_experts %}
	  <div class="sequence-active"></div>
	  <div class="sequences-current-resource">
	  </div>
	  <div class="sequences-all">
	  </div>
	  {% endif %}
	</li>
	{% endfor %}
      </ul>
    </div>

    <!-- Controls -->
    <a class="jcarousel-control-prev" href="#"><i class="icon-chevron-sign-left icon-4x"></i></a>
    <a class="jcarousel-control-next" href="#"><i class="icon-chevron-sign-right icon-4x"></i></a>
    </div>

    {% if user_is_admin or collection.sequencing_experts %}
    <ul class="list-group col-md-2 pull-right">
      <li class="list-group-item"><h3>SEQUENCES</h3></li>
      <li class="list-group-item">
	<a href="#" class="btn btn-primary btn-xs" role="button" id="sequence-create">Create</a>
	<a href="#" class="btn btn-default btn-xs" role="button" id="selection-clear">Clear</a>
      </li>
      <div id="sequence-detail" class="help-text">
      </div>
      <li class="list-group-item">
	<span id="sequence-update-button"></span>
	<span id="sequence-delete-button"></span>
      </li>
    </ul>
    {% endif %}

  </div>
</div>

trapper/apps/media_classification/templates/media_classification/index.html
{% extends "media_classification/base.html" %}

{% block content %}
Welcome to Animal Observation module!
<br />
(Intro here)
<br />
{% endblock content %}

trapper/apps/media_classification/templates/media_classification/project_detail.html
{% extends "media_classification/base.html" %}
{% load staticfiles %}
{% block content %}

<div class="panel panel-primary">
  <div class="panel-heading">
    Classification project details:
  </div>
  <div class="panel-body">
    <ul class="list-group">
      <li class="list-group-item">Name: {{project.name}}</li>
      <li class="list-group-item">
	Part of research project: <a href="{{project.research_project.get_absolute_url}}">{{project.research_project.name}}</a>
      </li>
    </ul>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    Researchers in this project:
  </div>
  <div class="panel-body">
    <table class="table">
      <th>User</th>
      <th>Role</th>
      {% for role in project.projectrole_set.all %}
      <tr><td>{{role.user.username}}</td><td>{{role.get_name_display}}</td></tr>
      {% endfor %}
    </table>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    Resource Collections for this project:
  </div>
  <div class="panel-body">
    <div class="panel-group" id="accordion">
      {% for pc in project.projectcollection_set.all %}
      <div class="panel panel-default">
	<div class="panel-heading">
	  <a data-toggle="collapse" data-parent="#accordion" href="#collection{{pc.pk}}">{{pc.collection.collection.name}}</a>
	  Active: <span class="glyphicon glyphicon-{% if pc.active %}ok{% else %}remove{% endif %}"></span>
	  Crowd-Sourcing: <span class="glyphicon glyphicon-{% if pc.cs_enabled %}ok{% else %}remove{% endif %}"></span>
	</div>
	<div id="collection{{pc.pk}}" class="panel-collapse collapse out">
	  <table class="table">
	    <th>Name</th>
	    <th>Owner</th>
	    <th>Uploader</th>
	    <th>Details</th>
	    <th>Classify</th>
	    {% for resource in pc.collection.collection.resources.all %}
	    <tr>
	      <td>{{ resource.name }}</td>
	      <td>{{ resource.owner.username }}</td>
	      <td>{{ resource.uploader.username }}</td>
	      <td><a href="{% url "storage:resource_detail" resource.id %}" title="Details"><span class="glyphicon glyphicon-search"></span></a></td>
	      <td><a href="{% url "media_classification:classify" project.id resource.id pc.id %}" title="Classify Resource"><span class="glyphicon glyphicon-eye-open"></span></a></td>
	    </tr>
	    {% endfor %}
	  </table>
	</div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

trapper/apps/media_classification/templates/media_classification/project_list.html
{% extends "media_classification/base.html" %}
{% load staticfiles %}
{% block media_classification_project_list %} class="active" {% endblock %}
{% block content %}
{% if items %}
Available projects:
<table class="table">
<th>Project name</th>
<th>Parent research project</th>
<th>Project staff</th>
<th>Details</th>
<th>Edit</th>
{% for project, can_view, can_edit in items %}
<tr>
	<td>{{ project.name }}</td>
	<td>{{ project.research_project.name }}</td>
	<td>
		{% for r in project.research_project.projectrole_set.all %}
		<a href="{{r.user.userprofile.get_absolute_url}}">{{r.user}}</a>({{r.get_name_display}}),
		{% endfor %}
	</td>
	<td>
		{% if can_view %}
		<a href="{% url "media_classification:project_detail" project.id %}"><span class="glyphicon glyphicon-search"></span></a>
		{% else %}
		<span class="glyphicon glyphicon-ban-circle"></span>
		{% endif %}
	</td>
	<td>
		{% if can_edit %}
		<a href="{% url "media_classification:project_update" project.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
		{% else %}
		<span class="glyphicon glyphicon-ban-circle"></span>
		{% endif %}
	</td>
</tr>
{% endfor %}
</table>
{% else %}
No project available. Start one now!
{% endif %}
{% endblock content %}