trapper/apps/accounts/urls.py
from django.conf.urls import patterns, url

from trapper.apps.accounts import views

urlpatterns = patterns('',
	url(r'profile/$', views.SessionUserProfileDetailView.as_view() , name='userprofile_detail' ),
	url(r'profile/detail/(?P<pk>\d+)/$', views.UserProfileDetailView.as_view() , name='userprofile_detail' ),
	url(r'profile/update/(?P<pk>\d+)/$', views.UserProfileUpdateView.as_view() , name='userprofile_update' ),
	url(r'login/$', 'django.contrib.auth.views.login', name='login' ),
	url(r'register/$', views.UserRegistrationView.as_view(), name='register' ),
	url(r'logout/$', views.logout_action, name='logout' ),
)

trapper/apps/geomap/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, UpdateView, ListView, CreateView, TemplateView, DeleteView

from trapper.apps.geomap import views
from.models import Location

urlpatterns = patterns('',
	# Index view:
	url(r'^$', TemplateView.as_view(template_name='geomap/index.html'), name='index'),
	url(r'location/detail/(?P<pk>\d+)/$', views.LocationDetailView.as_view(), name='location_detail'),
	url(r'location/list/$', views.LocationListView.as_view(), name='location_list'),
	url(r'location/upload/$', views.LocationUploadView.as_view(), name='location_upload'),
        url(r'location/geojson$', views.TrapperMapLayerView.as_view(model=Location), name='locations'),
        url(r'location/filterform$', views.LocationFilterFormView.as_view(), name="locations_filterform"),
        url(r'location/resources/$', views.LocationResourcesView.as_view(), name="location_resources"),
        url(r'location/collections/$', views.LocationCollectionAjaxView.as_view(), name="location_collections"),

        url(r'map/list/$', views.MapListView.as_view(), name="map_list"),
)

trapper/apps/messaging/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from trapper.apps.messaging import views

urlpatterns = patterns('',
	url(r'^$', TemplateView.as_view(template_name="messaging/index.html"), name='index'),
	url(r'message/detail/(?P<pk>\d+)/$', views.MessageDetailView.as_view(), name='message_detail'),
	url(r'message/inbox/$', views.MessageInboxView.as_view(), name='message_inbox'),
	url(r'message/outbox/$', views.MessageOutboxView.as_view(), name='message_outbox'),
	url(r'message/create/$', views.MessageCreateView.as_view(), name='message_create'),
	url(r'cnotification/list/$', views.CollectionNotificationListView.as_view(), name='cnotification_list'),
	url(r'rnotification/list/$', views.ResourceNotificationListView.as_view(), name='rnotification_list'),
	url(r'cnotification/resolve/(?P<pk>\d+)/$', views.ResolveCollectionRequestView.as_view(), name='cnotification_resolve'),
        url(r'rnotification/resolve/(?P<pk>\d+)/$', views.ResolveResourceRequestView.as_view(), name='rnotification_resolve'),
)

trapper/apps/research/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from trapper.apps.research import views


urlpatterns = patterns('',
	# Home page of research project module
	url(r'^$', TemplateView.as_view(template_name='research/index.html'), name='index'),

	# Display project list and the details about given project
	url(r'project/list/$', views.ProjectListView.as_view(), name='project_list'),
	url(r'project/detail/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
	url(r'project/create/$', views.ProjectCreateView.as_view(), name='project_create'),
	url(r'project/update/(?P<pk>\d+)/$', views.ProjectUpdateView.as_view(), name='project_update'),
	url(r'project/delete/(?P<pk>\d+)/$', views.ProjectDeleteView.as_view(), name='project_delete'),
	url(r'project/collection/create/$', views.ProjectCollectionCreateView.as_view(), name='project_collection_create'),
)

trapper/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
                # Trapper homepage
                url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
                url(r'^msg/$', TemplateView.as_view(template_name='base.html'), name='msg'),
                # Media classification urls
                url(r'^media_classification/', include('trapper.apps.media_classification.urls', namespace='media_classification')),
                # Research urls
                url(r'^research/', include('trapper.apps.research.urls', namespace='research')),
                # Storage urls
                url(r'^storage/', include('trapper.apps.storage.urls', namespace='storage')),
                # Messaging urls
                url(r'^messaging/', include('trapper.apps.messaging.urls', namespace='messaging')),
                # Accounts urls
                url('', include('django.contrib.auth.urls')),
                url(r'^accounts/', include('trapper.apps.accounts.urls', namespace='accounts')),
                # GeoMap urls
                url(r'^geomap/', include('trapper.apps.geomap.urls', namespace='geomap')),
                # Comments
                url(r'^comments/', include('fluent_comments.urls')),
                url(r'^tinymce/', include('tinymce.urls')),
                url(r'^grappelli/', include('grappelli.urls')),
                url(r'^admin/', include(admin.site.urls)),
                url(r'^admin_gis/', include(admin_gis.site.urls)),
                url(r'', include('leaflet_storage.urls')),
                url(r"^select2/", include("django_select2.urls")),
               )

if settings.DEBUG:
        urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        '''
	urlpatterns = patterns('',
                url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),
                url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
	) + urlpatterns
        '''

trapper/apps/media_classification/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django import forms
from django.conf import settings
from django.db.models import get_model

from trapper.apps.storage.models import Resource
from trapper.apps.research.models import Project as RProject, ProjectCollection as RProjectCollection
from django_select2.fields import AutoModelSelect2Field

from django_hstore import hstore

import json
from operator import itemgetter
from collections import OrderedDict


class Project(models.Model):
    """Describes a single classification project existing withing the system
    """

    name = models.CharField(max_length=255)
    research_project = models.ForeignKey(RProject, related_name='classification_projects')
    collections = models.ManyToManyField(RProjectCollection, through='ProjectCollection', blank=True, null=True, related_name="classifications")
    """Collections assigned to the project"""
    createdby = models.ForeignKey(User, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, default='2014-01-01 12:00:00')
    sequencing_enabled = models.BooleanField("Sequences", default=True, help_text="Enable sequencing interface")
    cs_enabled = models.BooleanField(default=True)
    """Is crowd-sourcing enabled for the project ?"""

    def __unicode__(self):
        return unicode(self.name)

    def get_all_cs_resources(self):
        """Returns a list of crowd-sourcing enabled resources for given project."""

        resources = []

        if not self.cs_enabled:
            return resources

        for c in self.projectcollection_set.filter(cs_enabled=True):
            new = [r for r in c.collection.resources.all()]
            resources.extend(new)
        return list(set(resources))

    def is_project_admin(self, user):
        role = self.cproject_roles.filter(user=user)
        return len(role) > 0 and role[0].name == 'A'

    # TODO: given user can have only one role in a project; rewrite tests below
    def determine_roles(self, user):
        """Returns a tuple of project roles for given user.

        :param user: user for which the roles are determined
        :type user: :py:class:`django.contrib.auth.models.User`
        :return: list of role names of given user withing the project
        :rtype: str
        """

        return [r.name for r in self.cproject_roles.filter(user=user)]

    def can_update(self, user):
        """Determines whether given user can update the project.

        :param user: user for which the test is made
        :type user: :py:class:`django.contrib.auth.models.User`
        :return: True if user can edit the project, False otherwise
        :rtype: bool
        """

        return self.cproject_roles.filter(user=user, name__in=ProjectRole.ROLE_EDIT).count() > 0

    def can_detail(self, user):
        """Determines whether given user can see the details of a project.

        :param user: user for which the check is made
        :type user: :py:class:`django.contrib.auth.models.User`
        :return: True if user can see the details of the project, False otherwise
        :rtype: bool
        """

        return self.cproject_roles.filter(user=user).count() > 0

    def get_absolute_url(self):
        return reverse('media_classification:project_detail', kwargs={'pk':self.pk})


class ProjectCollection(models.Model):
    """Many-To-Many model for Project-Collection relationship."""

    project = models.ForeignKey(Project)
    collection = models.ForeignKey(RProjectCollection)
    active = models.BooleanField("Active", default=True)
    """Is collection "active" within the project at given moment ?"""
    group_by_location = models.BooleanField("Group resources by location", default=False)
    """Should resources for this collection be grouped by location in classification view?"""
    sequencing_experts = models.BooleanField("Sequences editable by experts", default=True, help_text="Allow experts to create and edit sequences")
    cs_enabled = models.BooleanField("Crowd-Sourcing", default=True, help_text="Enable Crowd-Sourcing")
    """Is collection available for the crowd-sourcing ?"""

    def __unicode__(self):
        return unicode("%s" % self.collection)

    def get_resources(self):
        return self.collection.collection.resources.all().order_by('date_recorded', 'name')

    def get_resources_with_status(self):
        resources = self.get_resources()
        resources_pks = resources.values_list('pk', flat=True)
        status_list = Classification.objects.filter(
            project__pk=1, resource__pk__in=resources_pks
        ).values_list('approved', flat=True).order_by('resource__date_recorded', 'resource__name')
        return zip(resources, status_list)

#---------------------------------------------------------------#


class AttributeSet(models.Model):
    """Defined group of attributes describing given classification form.
    Such set is defined per-resource type, and is defined in given classification project.
    """

    CUSTOM_ATTRS_FIELDS = {
        'B': forms.BooleanField,
        'F': forms.FloatField,
        'I': forms.IntegerField,
        'S': forms.CharField,
    }

    name = models.CharField(max_length=255)
    project = models.OneToOneField(Project, verbose_name='Media classification project', null=True, blank=True, related_name="attributeset")
    predefined_attrs = hstore.DictionaryField(null=True, blank=True)
    custom_attrs = hstore.DictionaryField(null=True, blank=True)
    dynamic_attrs_order = models.TextField(null=True, blank=True)
    static_attrs_order = models.TextField(null=True, blank=True)
    owner = models.ForeignKey(User, null=True, blank=True, related_name='owned_attsets')

    objects = hstore.HStoreManager()

    def __unicode__(self):
        return unicode("Name: %s | Project: %s" % (self.name, self.project.name))

    def get_absolute_url(self):
        return reverse('media_classification:attributeset_detail', kwargs={'pk':self.pk})

    def can_edit(self, user):
        return self.owner == user

    def get_pre_attrs_names(self):
        return settings.PREDEFINED_ATTRIBUTES_SIMPLE.keys() + settings.PREDEFINED_ATTRIBUTES_MODELS.keys()

    def get_active_pre_attrs_names(self):
        config = self.get_pre_attrs_names()
        active = []
        for attr in config:
            if self.predefined_attrs[attr] == 'true':
                active.append(attr)
        return active

    def get_all_attrs_names(self):
        all = [[],[]] # [[dynamic_form], [static_form]]
        for at in self.get_active_pre_attrs_names():
            if self.predefined_attrs['target_%s' % at] == 'D':
                all[0].append(at)
            else:
                all[1].append(at)
        for at in self.custom_attrs.keys():
            if json.loads(self.custom_attrs[at])['target'] == 'D':
                all[0].append(at)
            else:
                all[1].append(at)
        return all

    def get_dynamic_attrs_order(self):
        try:
            return self.dynamic_attrs_order.split(',')
        except:
            return []

    def get_static_attrs_order(self):
        try:
            return self.static_attrs_order.split(',')
        except:
            return []

    def update_attrs_order(self):
        all_attrs_names = self.get_all_attrs_names()
        dynamic_attrs_order = self.get_dynamic_attrs_order()
        static_attrs_order = self.get_static_attrs_order()
        ordered_attrs = []
        new_attrs = []
        for at in all_attrs_names[0]: # dynamic_form
            if not at in dynamic_attrs_order:
                dynamic_attrs_order.append(at)
        for at in dynamic_attrs_order:
            if not at in all_attrs_names[0]:
                del dynamic_attrs_order[dynamic_attrs_order.index(at)]
        for at in all_attrs_names[1]: # static_form
            if not at in static_attrs_order:
                static_attrs_order.append(at)
        for at in static_attrs_order:
            if not at in all_attrs_names[1]:
                del static_attrs_order[static_attrs_order.index(at)]
        self.dynamic_attrs_order = ','.join(dynamic_attrs_order)
        self.static_attrs_order = ','.join(static_attrs_order)
        self.save()

    def parse_hstore_values(self, field, attr=None):
        parsed_values = {}
        # if attr not specified parse all
        if not attr:
            items = getattr(self, field).items()
        else:
            items = [(attr, getattr(self, field)[attr], ),]
        for k,v in items:
            try:
                parsed_values[k] = json.loads(v)
            except ValueError:
                # if it is not a json it must be a simple string so just add it to a parsed_values dict
                parsed_values[k] = v
        return parsed_values

    def prepare_class_form_fields_defs(self):
        # parsed custom attributes
        ca = self.parse_hstore_values('custom_attrs')
        # parsed predefined attributes
        pa = self.parse_hstore_values('predefined_attrs')
        form_fields = OrderedDict()
        form_fields['D'] = OrderedDict() # "D" -> dynamic form
        form_fields['S'] = OrderedDict() # "S" -> dynamic form
        # first prepare predefined attributes:
        pas = settings.PREDEFINED_ATTRIBUTES_SIMPLE
        pam = settings.PREDEFINED_ATTRIBUTES_MODELS
        for key in pas.keys():
            if pa.get(key):
                if pas[key].get('widget'):
                    widget = pas[key]['widget']
                    formfield = pas[key]['formfield'](required=pa['required_%s' % key] ,widget=widget)
                else:
                    formfield = pas[key]['formfield'](required=pa['required_%s' % key])
                form_fields[pa['target_%s' % key]][key] = formfield
        for key in pam.keys():
            if pa.get(key):
                model = get_model(pam[key]['app'], key)

trapper/apps/accounts/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.views import generic
from django.core.urlresolvers import reverse_lazy


class UserRegistrationView(generic.FormView):
    """Displays the user registration form and creates a new user."""

    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "<strong>Account Created!</strong>Please login using your username and password.")
        return super(UserRegistrationView, self).form_valid(form)

class UserProfileDetailView(generic.DetailView):
    """Displays the profile details about an arbitrary user."""

    model = User
    template_name = "accounts/user_detail.html"
    context_object_name = 'u'

class SessionUserProfileDetailView(UserProfileDetailView):
    """Displays the profile details about user stored in session."""

    def get_object(self):
        return self.request.user

class UserProfileUpdateView(generic.UpdateView):
    """Update view for the user profile."""

    model = User
    template_name = "accounts/user_update.html"
    context_object_name = 'u'
    fields = ['username','first_name','last_name','email']

    def get_success_url(self):
        return reverse_lazy('accounts:userprofile_detail', kwargs={'pk':self.request.user.pk,})

def logout_action(request):
    logout(request)
    return redirect('trapper.apps.accounts.login')

trapper/templates/actions_select.html
{% load i18n %}
<div class="form-group">
<div class="controls ">
<select name="action" id="id_action" class="select form-control">
    <option value="-1">--------</option>
    {% for action, attrs in actions %}
        <option {% if attrs.class %}class="{{attrs.class}}"{% endif %} value="{{ forloop.counter }}"> {{ action }}</option>
    {% endfor %}
</select>
</div>
</div>
<button class="btn btn-default" type="submit"> Run action</button>
<a href="#" onclick="selectAll()">select all ({{ paginator.count }})</a>
<input type="hidden" value="{{ paginator.count }}" name="all-items-count">
<input id="select-across" type="hidden" value="0" name="select-across">

<script type="text/javascript">
    var selectAll = function() {
	$('#select-across').val(1);
    }
</script>

trapper/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- CSS -->
    <link type="text/css" href="{% static "jquery/jquery-ui-1.10.4.min.css" %}"  media="all" rel="stylesheet" />
    <link type="text/css" href="{% static "bootstrap/css/bootstrap.css" %}"  media="all" rel="stylesheet" />
    <link type="text/css" href="{% static "bootstrap/css/bootstrap-theme.css" %}"  media="all" rel="stylesheet" />
    <link type="text/css" href="{% static "bootstrap/css/bootstrap-datetimepicker.min.css" %}"  media="all" rel="stylesheet" />
    <link type="text/css" href="{% static "bootstrap/css/bootstrap-switch.min.css" %}"  media="all" rel="stylesheet" />
    <link type="text/css" href="{% static "bootstrap/css/select2-bootstrap.css" %}"  media="all" rel="stylesheet" />
    <link type="text/css" href="{% static "bootstrap_extra.css" %}"  media="all" rel="stylesheet" />
    <link type="text/css" href="{% static "font-awesome/css/font-awesome.min.css" %}" media="all" rel="stylesheet" />

    <!-- JS -->
    <script type="text/javascript" src="{% static "jquery/jquery-2.1.0.min.js" %}"></script>
    <script type="text/javascript" src="{% static "jquery/jquery-ui-1.10.4.min.js" %}"></script>
    <script type="text/javascript" src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "bootstrap/js/bootstrap-datetimepicker.min.js" %}"></script>
    <script type="text/javascript" src="{% static "bootstrap/js/bootstrap-switch.min.js" %}"></script>
    <script type="text/javascript">
      jQuery(function ($) {
	  $('.datetimeinput').datetimepicker({
	      format: 'yyyy-mm-dd hh:ii',
	  });
      });
    </script>
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">
    
    <title>Trapper</title>

    {# Header block for extra scripts and css styles #}
    {% block header %}{% endblock header %}


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      
      <!-- Static navbar -->
      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	  <a class="navbar-brand" href="{% url "index" %}"><span class="glyphicon glyphicon-home"></span> Trapper</a>
        </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">

	    {% if user.is_staff %}
	    <li><a href="{% url "admin:index" %}"><span class="glyphicon glyphicon-briefcase"></span> Admin Site</a></li>
	    {% endif %}
	    <li class="dropdown">
	      
	      
	      {% if user.is_authenticated %}
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-envelope {%if user.userprofile.has_unread_messages %}new_message{% endif %}"></span> Messaging<b class="caret"></b></a>
	      
	      <ul class="dropdown-menu">
	        <li class="dropdown-header">Message:</li>
		<li><a href="{% url "messaging:message_inbox" %}">Inbox <span class="badge">{{ user.userprofile.count_unread_messages }}</span></a></li>
	        <li><a href="{% url "messaging:message_outbox" %}">Outbox</a></li>
	        <li><a href="{% url "messaging:message_outbox" %}">New message</a></li>
	        <li class="divider"></li>
	        <li class="dropdown-header">System Notifications:</li>
		<li><a href="{% url "messaging:cnotification_list" %}">Requested Collections <span class="badge">{{ user.userprofile.count_unresolved_collection_notifications }}</span></a></li>
		<li><a href="{% url "messaging:rnotification_list" %}">Requested Resources <span class="badge">{{ user.userprofile.count_unresolved_resource_notifications }}</span></a></li>	
	      </ul>
	    </li>
	    {% endif %}

            <li class="dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-film"></span> Storage<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="dropdown-header">Resources:</li>
                <li><a href="{% url "storage:resource_list" %}">Resources</a></li>
		{% if user.is_authenticated %}
                <li><a href="{% url "storage:user_resource_list" user.id %}">My resources</a></li>
		<li><a href="{% url "storage:resource_create" %}">Add resource <span class="glyphicon glyphicon-plus create_item"></span></a></li>
		{% endif %}
                <li class="divider"></li>
                <li class="dropdown-header">Collections:</li>
                <li><a href="{% url "storage:collection_list" %}">Collections</a></li>
		{% if user.is_authenticated %}
                <li><a href="{% url "storage:user_collection_list" user.id %}">My collections</a></li>
		<li><a href="{% url "storage:collection_create" %}">Add collection <span class="glyphicon glyphicon-plus create_item"></span></a></li>
		<li><a href="{% url "storage:collection_upload" %}">Upload collection <span class="glyphicon glyphicon-plus create_item"></span></a></li>
		{% endif %}
              </ul>
            </li>
	    
            <li class="dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-book"></span> Research<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="dropdown-header">Projects:</li>
		<li><a href="{% url "research:project_list" %}">Projects</a></li>
              </ul>
            </li>

            <li class="dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-eye-open"></span> Media classification<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="dropdown-header">Classification projects:</li>
		<li><a href="{% url "media_classification:project_list" %}">Projects</a></li>
		<li><a href="{% url "media_classification:attributeset_list" %}">Feature sets</a></li>
                <li><a href="#">Request collection</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Crowd Sourcing:</li>
                <li><a href="#">Tutorial</a></li>
              </ul>
            </li>

	    <li class="dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-globe"></span> GeoMap<b class="caret"></b></a>
              <ul class="dropdown-menu">
		<li><a href="{% url "geomap:index" %}">Show Map</a></li>
		<li><a href="{% url "geomap:location_upload" %}">Upload locations</a></li>
              </ul>
	    </li>

          </ul>

          <ul class="nav navbar-nav navbar-right">
	    {% if user.is_authenticated %}
	    <li><a href="{{user.userprofile.get_absolute_url}}"><span class="glyphicon glyphicon-user"></span> {{user.username}}</a></li>
	    <li><a href="{% url "accounts:logout" %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
	    {% else %}
	    <li><a href="{% url "accounts:login" %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
	    <li><a href="{% url "accounts:register" %}"><span class="glyphicon glyphicon-plus-sign"></span> Register</a></li>
	    {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
	</div><!--/.container-fluid -->
      </div>
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissable">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	{{ message|safe }}
      </div>
      {% endfor %}
      {% endif %}
      {% block master_content %}{% endblock master_content %}
      	
      <!-- <footer style="text-align:center;"> -->
      <!-- 	© 2013 Mammal Research Institute of the Polish Academy of Sciences -->
      <!-- 	and Bialystok University of Technology. -->
      <!-- 	<\!-- <a href="http://www.djangoproject.com/"><img src="https://www.djangoproject.com/m/img/badges/djangomade124x25.gif" border="0" alt="Made with Django." title="Made with Django." /></a> -\-> -->
      <!-- </footer> -->
    </div> <!-- /container -->
    
  </body>
</html>

trapper/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block master_content %}
<div class="jumbotron">
  <h2>Welcome to Trapper!</h2>
</div>
{% endblock master_content %}

trapper/templates/modal_form_template.html
<div class="modal fade" id="modal-form-template" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">
	  <div id="modal-form-title"></div>
	</h3>
      </div>
      <div class="modal-body">
	{% if messages %}
	{% for message in messages %}
	<div class="alert alert-{{ message.tags }} alert-dismissable">
	  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	  {{ message|safe }}
	</div>
	{% endfor %}
	{% endif %}
	<div id="modal-form-alert" class="alert hide"><strong><span id="modal-form-alert-msg"></span></strong></div>
	<div class="">
	    <div id="modal-form">
	    </div>
	</div>          
      </div>
      <div class="modal-footer">
	<span id="modal-form-submit-button"></span>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
 