trapper/apps/geomap/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, UpdateView, ListView, CreateView, TemplateView, DeleteView

from trapper.apps.geomap import views
from.models import Location

urlpatterns = patterns('',
	# Index view:
	url(r'^$', TemplateView.as_view(template_name='geomap/index.html'), name='index'),
	url(r'location/detail/(?P<pk>\d+)/$', views.LocationDetailView.as_view(), name='location_detail'),
	url(r'location/list/$', views.LocationListView.as_view(), name='location_list'),
	url(r'location/upload/$', views.LocationUploadView.as_view(), name='location_upload'),
        url(r'location/geojson$', views.TrapperMapLayerView.as_view(model=Location), name='locations'),
        url(r'location/filterform$', views.LocationFilterFormView.as_view(), name="locations_filterform"),
        url(r'location/resources/$', views.LocationResourcesView.as_view(), name="location_resources"),
        url(r'location/collections/$', views.LocationCollectionAjaxView.as_view(), name="location_collections"),

        url(r'map/list/$', views.MapListView.as_view(), name="map_list"),
)

trapper/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
                # Trapper homepage
                url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
                url(r'^msg/$', TemplateView.as_view(template_name='base.html'), name='msg'),
                # Media classification urls
                url(r'^media_classification/', include('trapper.apps.media_classification.urls', namespace='media_classification')),
                # Research urls
                url(r'^research/', include('trapper.apps.research.urls', namespace='research')),
                # Storage urls
                url(r'^storage/', include('trapper.apps.storage.urls', namespace='storage')),
                # Messaging urls
                url(r'^messaging/', include('trapper.apps.messaging.urls', namespace='messaging')),
                # Accounts urls
                url('', include('django.contrib.auth.urls')),
                url(r'^accounts/', include('trapper.apps.accounts.urls', namespace='accounts')),
                # GeoMap urls
                url(r'^geomap/', include('trapper.apps.geomap.urls', namespace='geomap')),
                # Comments
                url(r'^comments/', include('fluent_comments.urls')),
                url(r'^tinymce/', include('tinymce.urls')),
                url(r'^grappelli/', include('grappelli.urls')),
                url(r'^admin/', include(admin.site.urls)),
                url(r'^admin_gis/', include(admin_gis.site.urls)),
                url(r'', include('leaflet_storage.urls')),
                url(r"^select2/", include("django_select2.urls")),
               )

if settings.DEBUG:
        urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        '''
	urlpatterns = patterns('',
                url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),
                url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
	) + urlpatterns
        '''

trapper/apps/geomap/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import User

class Location(models.Model):
    """Single location (Point) on map.
    This model is often referred by other models for establishing a spatial context.
    """

    coordinates = models.PointField(srid=4326)
    objects = models.GeoManager()
    location_id = models.CharField(max_length=100, unique=True)

    owner = models.ForeignKey(User, related_name='owned_locations')
    managers = models.ManyToManyField(User, related_name='managed_locations', null=True, blank=True)
    is_public = models.BooleanField(default=False)

    def can_view(self, user):
        """Determines whether user can view the location.
        :param user: user for which the test is made
        :type user: :py:class:`django.contrib.auth.User`
        :return: True if user can see the location, False otherwise
        :rtype: bool
        """

        return self.is_public or user == self.owner or user in self.managers.all()

    def __unicode__(self):
        return unicode("Location ID: %s" % (self.location_id, ))

trapper/apps/geomap/forms.py
from django import forms

from trapper.apps.geomap.models import Location
from trapper.apps.storage.models import Resource
import trapper.tools.gpxpy as gpxpy
from django.contrib.gis.geos import Point
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Field


resource_types = [(k) for k in Resource.TYPE_CHOICES]
resource_types.sort()
RESOURCE_TYPE_CHOICES = tuple([('','-- All --')]+resource_types)
resource_status = [(k) for k in Resource.STATUS_CHOICES]
RESOURCE_STATUS_CHOICES = tuple([('','-- All --')]+resource_status)
IS_PUBLIC_CHOICES = (
    ('', '-- All --'),
    (True, 'True'),
    (False, 'False')
)

class LocationFilterForm(forms.ModelForm):

    resource__resource_type = forms.ChoiceField(choices=RESOURCE_TYPE_CHOICES, label='Type', required=False)
    resource__status = forms.ChoiceField(choices=RESOURCE_STATUS_CHOICES, required=False)
    is_public = forms.ChoiceField(choices=IS_PUBLIC_CHOICES, required=False)

    class Meta:
        model = Location
        exclude = ['owner',]

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_id = 'filter-locations-form'
        self.helper.error_text_inline = True
        self.helper.form_show_errors = False
        self.helper.help_text_inline = False
        self.helper.form_show_labels = True
        self.helper.layout = Layout(
            Fieldset(
                'Location properties',
                'is_public',
            ),
            Fieldset(
                'Resources properties',
                'resource__resource_type',
                'resource__status',
            ),
        )
        super(LocationFilterForm, self).__init__(*args, **kwargs)


class LocationUploadForm(forms.Form):
    """Upload form for the locations file."""

    gpx_file=forms.FileField()
    is_public = forms.BooleanField(initial=False, required=False)

    def add_locations(self, user):
        """Parses the .gpx file and looks for the locations which aren't available in the system yet.

        :param user: user adding the locations (made the Location's owner)
        :type user: :py:class:`django.contrib.auth.models.User`
        """

        gpx_file = self.cleaned_data['gpx_file']
        gpx = gpxpy.parse(gpx_file)
        no_created = 0
        for waypoint in gpx.waypoints:
            if Location.objects.filter(location_id=waypoint.name).count() == 0:
                no_created += 1
                Location.objects.create(location_id=waypoint.name,
                                        coordinates=Point(waypoint.longitude, waypoint.latitude),
                                        owner=user,
                                        is_public=self.cleaned_data['is_public']
                )
        return no_created

trapper/apps/geomap/views.py
from django.contrib import messages
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.shortcuts import render_to_response
from django.template import RequestContext

from braces.views import LoginRequiredMixin, JSONResponseMixin, AjaxResponseMixin
from leaflet_storage.views import MapView, MapNew
from crispy_forms.utils import render_crispy_form
from crispy_forms.layout import Layout, Fieldset

from trapper.apps.geomap.models import Location
from trapper.apps.storage.models import Resource, Collection
from trapper.apps.geomap.forms import LocationUploadForm, LocationFilterForm
from trapper.apps.storage.filters import ResourceFilter

class LocationDetailView(generic.DetailView):
    """Displays given location on the map.
    """
    model = Location
    context_object_name = 'location'
    template_name = 'geomap/location_detail.html'

class LocationListView(generic.ListView):
    """Displays list of locations.
    """
    model = Location
    context_object_name = 'locations'
    template_name = 'geomap/location_list.html'

class LocationUploadView(LoginRequiredMixin, generic.FormView):
    """Uploads location data from the gpx file.
    """

    template_name = 'geomap/location_upload.html'
    form_class = LocationUploadForm
    success_url = reverse_lazy('geomap:location_list')

    def form_valid(self, form):
        """Attaches a message once the form was validated."""

        new_locs = form.add_locations(self.request.user)

        if new_locs == 0:
            messages.warning(self.request, "<strong>Upload Info:</strong> No new Locations found!")
        elif new_locs == 1:
            messages.success(self.request, "<strong>Upload Info:</strong> %d new Location was added!" % (new_locs,))
        elif new_locs > 1:
            messages.success(self.request, "<strong>Upload Info:</strong> %d new Locations were added!" % (new_locs,))

        return super(LocationUploadView, self).form_valid(form)

from djgeojson.views import GeoJSONLayerView
from .filters import LocationFilter


class TrapperMapLayerView(LoginRequiredMixin, GeoJSONLayerView):
    # Options
    precision = 5   # float
    geometry_field = 'coordinates'
    properties = ['pk', 'location_id', 'owner', 'is_public',]
    model = Location
    search_fields = ('owner__username', 'location_id', 'resource__name')


    def get_queryset(self, *args, **kwargs):
        qs = super(TrapperMapLayerView, self).get_queryset(*args, **kwargs)
        # TODO: use permissions; in general user can map either his/her own resources (owner or manager) or collections
        # so there are only 2 cases: a) filter for user reosurces b) check if user really have perms for given collection
        # user can view given location when 1) is owner or manager 2) has perms to view at least 1 resource linked to this location
        collection_pk = self.request.GET.get('collection_pk')
        if collection_pk:
            qs = qs.filter(resource__collection__pk=collection_pk).distinct()
        filters = LocationFilter(self.request.GET, queryset=qs)
        qs = filters.qs.distinct()
        search = self.request.GET.get('q')
        if search:
            search_words = search.split()
            filters = None
            for f in self.search_fields:
                for word in search_words:
                    q = Q(**{f + '__icontains': word})
                    filters = filters | q if filters else q
            if filters:
                qs = qs.filter(filters)
        return qs


class LocationFilterFormView(JSONResponseMixin, AjaxResponseMixin, generic.View):

    def get_ajax(self, request, *args, **kwargs):
        location_form = render_crispy_form(LocationFilterForm(request.GET))
        return self.render_json_response({'location_form_html': location_form,})


class LocationResourcesView(generic.View):

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            location_pk = request.GET.get('location_pk')
            if location_pk:
                location = Location.objects.get(pk=location_pk)
                #TODO: user permissions
                qs = Resource.objects.filter(location=location)
                filtered = ResourceFilter(request.GET, queryset=qs)
                template = 'geomap/location_detail_map.html'
                data = {
                    'resources': filtered.qs,
                    'location': location,
                }
                return render_to_response(template, data, context_instance = RequestContext(request))


# get names of requested collections
class LocationCollectionAjaxView(JSONResponseMixin, AjaxResponseMixin, generic.View):

    def get_ajax(self, request, *args, **kwargs):
        qs = Collection.objects.filter(pk__in=request.GET['collections'].split(',')).values('pk', 'name').order_by('name')
        return self.render_json_response(list(qs))


from leaflet_storage.models import Map
class MapListView(generic.ListView):
    model = Map
    context_object_name = 'maps'
    template_name = 'geomap/map_list.html'

trapper/apps/geomap/templates/geomap/base.html
{% extends "base.html" %}

{% block master_content %}
<p>
<ul class="nav nav-pills">
	<li {% block geomap_index %}{% endblock %}><a href="{% url "geomap:index" %}">Map</a></li>
	<li {% block geomap_location_list %}{% endblock %}><a href="{% url "geomap:location_list" %}">Locations</a></li>
</ul>
</p>
<p>
{% block content %}{% endblock content %}
</p>
{% endblock master_content %}

trapper/apps/geomap/templates/geomap/index.html
{% extends "geomap/base.html" %}

{% load staticfiles %}

{% block header %}
<script type="text/javascript" src="{% static "jquery.js" %}"></script>
<script type="text/javascript" src="{% static "OpenLayers.js" %}"></script>
<script type="text/javascript">
	(function($){
		window.onload=function(){
		    map = new OpenLayers.Map('geomap');

			var base_layer = new OpenLayers.Layer.OSM("Simple OSM Layer");

			map.addControls([
				new OpenLayers.Control.LayerSwitcher(),
			    new OpenLayers.Control.Navigation(),
			    new OpenLayers.Control.Attribution(),
			    new OpenLayers.Control.PanZoomBar()
			]);

			map.addLayers([base_layer]);

            map.setCenter(
                new OpenLayers.LonLat(23.860759, 52.701501).transform(
                    new OpenLayers.Projection("EPSG:4326"),
					new OpenLayers.Projection("EPSG:900913"), // to Spherical Mercator Projection
                    map.getProjectionObject()
                ), 12
            ); 
		}
		})(jQuery);
</script>
{% endblock header %}

{% block geomap_index %}class="active"{% endblock %}

{% block content %}
<div class="panel panel-primary">
	<div class="panel-heading">Map view</div>
	<div class="panel-body">
		<div style="height:500px; width:100%" id="geomap"></div>
	</div>
</div>
{% endblock content %}

trapper/apps/geomap/templates/geomap/leaflet_map_full.html
{% extends "leaflet_storage/map_detail.html" %}

{% load staticfiles %}

{% block title %}{{ map.name }}{% endblock %}
{% block body_class %}map_detail{% endblock %}

{% block header %}
    {{ block.super }}
    <script type="text/javascript" src="{% static "jquery/jquery-2.1.0.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/geomap.js" %}"></script>
    <link type="text/css" href="{% static "css/geomap.css" %}"  media="all" rel="stylesheet" />
{% endblock %}

{% block content %}
    {% block map_init %}
        {% include "leaflet_storage/map_init.html" %}
    {% endblock %}
    {% include "leaflet_storage/map_messages.html" %}    
{% endblock %}

trapper/apps/geomap/templates/geomap/location_detail.html
{% extends "geomap/base.html" %}

{% load staticfiles %}

{% block header %}
<script type="text/javascript" src="{% static "jquery.js" %}"></script>
<script type="text/javascript" src="{% static "OpenLayers.js" %}"></script>
<script type="text/javascript">
	(function($){
		window.onload=function(){
		    map = new OpenLayers.Map('geomap');

			var base_layer = new OpenLayers.Layer.OSM("Simple OSM Layer");

			map.addControls([
				new OpenLayers.Control.LayerSwitcher(),
			    new OpenLayers.Control.Navigation(),
			    new OpenLayers.Control.Attribution(),
			    new OpenLayers.Control.PanZoomBar()
			]);

			map.addLayers([base_layer]);

			var markers = new OpenLayers.Layer.Markers("Markers");

			var size = new OpenLayers.Size(21,25);
			var offset = new OpenLayers.Pixel(-(size.w/2), -size.h);

			var waypoint = {
			    lat: "{{location.coordinates.x}}",
			    lng: "{{location.coordinates.y}}"
			};
			
			markers.addMarker(new OpenLayers.Marker(new OpenLayers.LonLat(waypoint.lat, waypoint.lng).transform (
			    new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
			    new OpenLayers.Projection("EPSG:900913"), // to Spherical Mercator Projection
                    map.getProjectionObject()
			)));
		    
			map.addLayer(markers);

            map.setCenter(
                new OpenLayers.LonLat(waypoint.lat, waypoint.lng).transform(
                    new OpenLayers.Projection("EPSG:4326"),
					new OpenLayers.Projection("EPSG:900913"), // to Spherical Mercator Projection
                    map.getProjectionObject()
                ), 12
            ); 
		}
		})(jQuery);
</script>
{% endblock header %}

{% block geomap_index %}class="active"{% endblock %}

{% block content %}
<div class="panel panel-primary">
	<div class="panel-heading">Map view</div>
	<div class="panel-body">
		<div style="height:500px; width:100%" id="geomap"></div>
	</div>
</div>
{% endblock content %}

trapper/apps/geomap/templates/geomap/location_detail_map.html
{% load thumbnail %}

<h2>Location: {{ location.location_id }}</h2>
<p><b>X</b>: {{ location.coordinates.x }}, <b>Y</b>: {{ location.coordinates.y }}</p>
<p>Owner: {{ location.owner }}</p>
{% if resources %}

{% for r in resources %}
<ul>
  <li>
    <h2>{{ r.name }}</h2>
    <a href="/storage/resource/detail/{{ r.pk }}/" target="_blank"><img src="{{ r.file|thumbnail_url:'default' }}" alt=""></a>
    <p>Date: {{ r.date_recorded }}, Type: {{ r.resource_type }}</p>
    <p>Owner: {{ r.owner }}</p>
  </li>
</ul>
{% endfor %}

{% else %}

<p>No resources for this location.</p>

{% endif %}

trapper/apps/geomap/templates/geomap/location_display.html
{% load staticfiles %}

{% block header %}
<script type="text/javascript" src="{% static "jquery.js" %}"></script>
<script type="text/javascript" src="{% static "OpenLayers.js" %}"></script>
<script type="text/javascript">
	(function($){
		window.onload=function(){
		    map = new OpenLayers.Map('geomap');

			var base_layer = new OpenLayers.Layer.OSM("Simple OSM Layer");

			map.addControls([
				new OpenLayers.Control.LayerSwitcher(),
			    new OpenLayers.Control.Navigation(),
			    new OpenLayers.Control.Attribution(),
			    new OpenLayers.Control.PanZoomBar()
			]);

			map.addLayers([base_layer]);

			var markers = new OpenLayers.Layer.Markers("Markers");

			var size = new OpenLayers.Size(21,25);
			var offset = new OpenLayers.Pixel(-(size.w/2), -size.h);

			var waypoint = {
			    lat: "{{location.coordinates.x}}",
			    lng: "{{location.coordinates.y}}"
			};
			
			markers.addMarker(new OpenLayers.Marker(new OpenLayers.LonLat(waypoint.lat, waypoint.lng).transform (
			    new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
			    new OpenLayers.Projection("EPSG:900913"), // to Spherical Mercator Projection
                    map.getProjectionObject()
			)));
		    
			map.addLayer(markers);

            map.setCenter(
                new OpenLayers.LonLat(waypoint.lat, waypoint.lng).transform(
                    new OpenLayers.Projection("EPSG:4326"),
					new OpenLayers.Projection("EPSG:900913"), // to Spherical Mercator Projection
                    map.getProjectionObject()
                ), 12
            ); 
		}
		})(jQuery);
</script>
{% endblock header %}
<div style="height:500px; width:1000px" id="geomap"></div>

trapper/apps/geomap/templates/geomap/location_list.html
{% extends "geomap/base.html" %}

{% load staticfiles %}
{% block geomap_location_list %}class="active"{% endblock %}
{% block content %}
<div class="panel panel-primary">
	<div class="panel-heading">Locations</div>
	<div class="panel-body">
		<table class="table">
			<thead>
				<tr>
					<th>ID</th>
					<th>Lat</th>
					<th>Lon</th>
					<th>Owner</th>
					<th>Is Public ?</th>
					<th>See on map</th>
				</tr>
			</thead>
			<tbody>
			{% for location in locations %}
			<tr>
				<td>{{ location.location_id }}</td>
				<td>{{ location.coordinates.x }}</td>
				<td>{{ location.coordinates.y }}</td>
				<td>{{ location.owner.username }}</td>
				<td>{{ location.is_public }}</td>
				<td><a href="{% url "geomap:location_detail" location.pk %}"><span class="glyphicon glyphicon-search"></span></a></td>
			</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock content %}

trapper/apps/geomap/templates/geomap/location_upload.html
{% extends "base.html" %}
{% block master_content %}
<div class="panel panel-primary">
	<div class="panel-heading">Upload locations</div>
	<div class="panel-body">
		<form role="form" action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		
		<div class="form-group">
			{% for error in form.non_field_errors %}
			<div class='alert alert-danger'>{{error}}</div>
			{% endfor %}
			<label for="id_{{form.gpx_file.name}}">Upload GPX file</label>
			<input type="file" id="id_{{ form.gpx_file.name }}" name="{{form.gpx_file.name}}"></input>
			{% for e in form.gpx_file.errors %} {{e}} {% endfor %}
			<p class="help-block">Select the GPX file above and click submit.</p>
			<label for="id_{{form.is_public.name}}">Make publicly available ?</label>
			{{form.is_public}}
			{% for e in form.is_public.errors %} {{e}} {% endfor %}
			<p class="help-block">When selected, location will be publicly visible.</p>
		</div>
		<input class="btn btn-primary" type="submit" value="Submit" />
		</form>
	</div>
</div>
{% endblock master_content %}

trapper/apps/geomap/templates/geomap/map_init.html
{% load leaflet_storage_tags %}
<div id="map"></div>
<script type="text/javascript">
  var MAP = new L.Storage.Map(
      "map", 
      {{ map_settings|notag|safe }}
  );
  MAP.on("layer", function(){
      alert("layer event!");
  });
  MAP.setView([51.505, -0.09], 13);
</script>

trapper/apps/geomap/templates/geomap/map_list.html
{% extends "geomap/base.html" %}

{% load staticfiles %}
{% block content %}
<div class="panel panel-primary">
  <div class="panel-heading">Locations</div>
  <div class="panel-body">
    <table class="table">
      <thead>
	<tr>
	  <th>Name</th>
	  <th>Owner</th>
	  <th>Modified</th>
	  <th></th>
	</tr>
      </thead>
      <tbody>
	{% for map in maps %}
	<tr>
	  <td>{{ map.name }}</td>
	  <td>{{ map.owner.get_full_name }}</td>
	  <td>{{ map.modified_at }}</td>
	  <td><a href="{{ map.get_absolute_url }}">View</a></td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}