trapper/apps/media_classification/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from trapper.apps.media_classification import views


urlpatterns = patterns('',
	# Home page of animal observation app
	url(r'^$', TemplateView.as_view(template_name='media_classification/index.html'), name='index'),

	# Display project list and the details about given project
	url(r'project/list/$', views.ProjectListView.as_view(), name='project_list'),
	url(r'project/detail/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
        url(r'project/update/(?P<pk>\d+)/$', views.ProjectUpdateView.as_view(), name='project_update'),
	url(r'project/create/(?P<rp_pk>\d+)/$', views.ProjectCreateView.as_view(), name='project_create'),

	# Attributeset views
	url(r'attributeset/detail/(?P<pk>\d+)/$', views.AttributeSetDetailView.as_view(), name='attributeset_detail'),
	url(r'attributeset/list/$', views.AttributeSetListView.as_view(), name='attributeset_list'),

        url(r'attributeset/create/$', views.AttributeSetCreateView.as_view(), name='attributeset_create'),
        url(r'attributeset/update/(?P<pk>\d+)/$', views.AttributeSetUpdateView.as_view(), name='attributeset_update'),
	#url(r'attributeset/delete/(?P<pk>\d+)/$', views.AttributeSetDeleteView, name='attributeset_delete'),

	# Sequence views
	url(r'sequence/detail/(?P<sequence_pk>\d+)/$', views.SequenceDetailAjaxView.as_view(), name='sequence_detail'),
	url(r'sequence/list/(?P<collection_pk>\d+)/$', views.SequenceListAjaxView.as_view(), name='sequence_list'),
	url(r'sequence/create/(?P<collection_pk>\d+)/$', views.SequenceCreateUpdateAjaxView.as_view(), name='sequence_create'),
	url(r'sequence/update/(?P<sequence_pk>\d+)/$', views.SequenceCreateUpdateAjaxView.as_view(), name='sequence_update'),
	url(r'sequence/delete/(?P<sequence_pk>\d+)/$', views.SequenceDeleteAjaxView.as_view(), name='sequence_delete'),

	# Display the classification form and process (action) it
	url(r'classify/(?P<project_id>\d+)/(?P<resource_id>\d+)/(?P<collection_id>\d+)/$', views.classify_resource, name='classify'),
	url(r'classify/(?P<project_id>\d+)/(?P<resource_id>\d+)/(?P<collection_id>\d+)/(?P<user_id>\d+)/$', views.classify_resource, name='classify_user'),
	#url(r'classify/action/$', views.process_classify, name='classify_action'),

	# Displays the details about given classification
	url(r'classification/detail/(?P<pk>\d+)/$', views.ClassificationDetailView.as_view(), name='classification_detail'),
 	url(r'classification/list/(?P<pk>\d+)/$', views.ClassificationListView.as_view(), name='classification_list'),
 	url(r'classification/delete/(?P<pk>\d+)/$', views.ClassificationDeleteView.as_view(), name='classification_delete'),

	#url(r'crowd/list/$', views.cs_resource_list, name='cs_resource_list'),
)

trapper/apps/research/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from trapper.apps.research import views


urlpatterns = patterns('',
	# Home page of research project module
	url(r'^$', TemplateView.as_view(template_name='research/index.html'), name='index'),

	# Display project list and the details about given project
	url(r'project/list/$', views.ProjectListView.as_view(), name='project_list'),
	url(r'project/detail/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
	url(r'project/create/$', views.ProjectCreateView.as_view(), name='project_create'),
	url(r'project/update/(?P<pk>\d+)/$', views.ProjectUpdateView.as_view(), name='project_update'),
	url(r'project/delete/(?P<pk>\d+)/$', views.ProjectDeleteView.as_view(), name='project_delete'),
	url(r'project/collection/create/$', views.ProjectCollectionCreateView.as_view(), name='project_collection_create'),
)

trapper/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
                # Trapper homepage
                url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
                url(r'^msg/$', TemplateView.as_view(template_name='base.html'), name='msg'),
                # Media classification urls
                url(r'^media_classification/', include('trapper.apps.media_classification.urls', namespace='media_classification')),
                # Research urls
                url(r'^research/', include('trapper.apps.research.urls', namespace='research')),
                # Storage urls
                url(r'^storage/', include('trapper.apps.storage.urls', namespace='storage')),
                # Messaging urls
                url(r'^messaging/', include('trapper.apps.messaging.urls', namespace='messaging')),
                # Accounts urls
                url('', include('django.contrib.auth.urls')),
                url(r'^accounts/', include('trapper.apps.accounts.urls', namespace='accounts')),
                # GeoMap urls
                url(r'^geomap/', include('trapper.apps.geomap.urls', namespace='geomap')),
                # Comments
                url(r'^comments/', include('fluent_comments.urls')),
                url(r'^tinymce/', include('tinymce.urls')),
                url(r'^grappelli/', include('grappelli.urls')),
                url(r'^admin/', include(admin.site.urls)),
                url(r'^admin_gis/', include(admin_gis.site.urls)),
                url(r'', include('leaflet_storage.urls')),
                url(r"^select2/", include("django_select2.urls")),
               )

if settings.DEBUG:
        urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        '''
	urlpatterns = patterns('',
                url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),
                url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
	) + urlpatterns
        '''

trapper/apps/messaging/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from trapper.apps.storage.models import Resource, Collection
from trapper.apps.research.models import Project


class Message(models.Model):
    """E-mail like messaging features among the users."""

    subject = models.CharField(max_length=50)
    """Message subject"""

    text = models.TextField(max_length=1000)
    """Message text (body)"""

    user_from = models.ForeignKey(User, related_name='sent_messages')
    user_to = models.ForeignKey(User, related_name='received_messages')
    date_sent = models.DateTimeField(auto_now_add=True)
    date_received = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return unicode("%s -> %s (sent: %s)" % (self.user_from, self.user_to, self.date_sent))

    def get_absolute_url(self):
        return reverse('messaging:message_detail', kwargs={'pk':self.pk})


class SystemNotification(models.Model):
    """Abstract class for various types of system notifications directed towards a user."""

    name = models.CharField(max_length=50)
    resolved = models.BooleanField(default=False)

    def __unicode__(self):
        return unicode("%s (%s)" % (self.name, self.__class__.__name__))

    def resolve(self):
        self.resolved=True
        self.save()

    class Meta:
        abstract = True


# TODO: more general approach needed i.e. combine CollectionRequest and ResourceRequest
class CollectionRequest(SystemNotification):
    """Notification about an incoming collection request for the media classification project"""

    user = models.ForeignKey(User, related_name='collection_notifications')
    message = models.ForeignKey(Message)
    project = models.ForeignKey(Project)
    collections = models.ManyToManyField(Collection, blank=True, null=True, related_name='collection_request')

    def resolve_yes(self):
        """Resolves the request positively and creates a ProjectCollection object."""

        self.resolve()
        for collection in self.collections.all():
            self.project.collections.through.objects.create(project=self.project, collection=collection)

    def resolve_no(self):
        """Resolves the request negatively."""
        self.resolve()

class ResourceRequest(SystemNotification):
    """Notification about an incoming collection request for the media classification project"""

    user = models.ForeignKey(User, related_name='resource_notifications')
    user_from = models.ForeignKey(User)
    message = models.ForeignKey(Message)
    resources = models.ManyToManyField(Resource, blank=True, null=True, related_name='resource_request')

    def resolve_yes(self):
        """Resolves the request positively and assign to a user view-permissions to requested resources"""
        from guardian.shortcuts import assign_perm
        self.resolve()
        for resource in self.resources.all():
            assign_perm("view_resource_SNG", self.user_from, resource)

    def resolve_no(self):
        """Resolves the request negatively."""
        self.resolve()

trapper/apps/research/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from tinymce.widgets import TinyMCE
from djangular.forms import NgModelFormMixin
from crispy_forms.helper import FormHelper

from trapper.apps.research.models import Project, ProjectRole, ProjectCollection


class ProjectForm(forms.ModelForm):
    """Project ModelForm for the Update/Create views"""

    class Meta:
        model = Project
        fields = ['name','description',]

    description = forms.CharField(widget=TinyMCE(attrs={'cols':60, 'rows':15}))

ProjectRoleFormset = inlineformset_factory(Project, ProjectRole, extra = 1)
"""Formset for the ProjectRole model"""


class ProjectCollectionForm(NgModelFormMixin, forms.ModelForm):

    REQUIRED_PROJECT_ROLES = [ProjectRole.ROLE_PROJECT_ADMIN, ProjectRole.ROLE_EXPERT]

    class Meta:
        model = ProjectCollection

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.error_text_inline = True
        self.helper.form_show_errors = True
        self.helper.help_text_inline = False
        super(ProjectCollectionForm, self).__init__(*args, **kwargs)
        self.fields['collection'].widget = forms.HiddenInput()
        if user:
            project_pks = set(role.project.pk for role in user.research_roles.filter(name__in = self.REQUIRED_PROJECT_ROLES))
            projects = Project.objects.filter(pk__in=project_pks)
            self.fields['project'].queryset = projects

    def clean(self):
        project = self.cleaned_data.get("project")
        collection = self.cleaned_data.get("collection")
        if ProjectCollection.objects.filter(project=project, collection=collection):
            raise forms.ValidationError("Project Collection already exists.")
        return self.cleaned_data

trapper/apps/research/views.py
from braces.views import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import PermissionDenied

from extra_views import InlineFormSet, CreateWithInlinesView, UpdateWithInlinesView, NamedFormsetsMixin

from trapper.apps.research.models import Project, ProjectRole
from trapper.apps.research.forms import ProjectForm, ProjectCollectionForm
from trapper.apps.common.decorators import ObjectAccessRequiredMixin
from trapper.apps.storage.models import Collection
from trapper.apps.common.views import AjaxFormMixin

class ProjectListView(generic.ListView):
    """List view of the Project model"""

    model = Project
    context_object_name = 'items'
    template_name = 'research/project_list.html'

    def get_queryset(self, *args, **kwargs):
        """Besides getting the queryset, determines the permissions for request.user.

        :return: a list of tuples, each containing the following: (:class:`.Project`, user_can_view, user_can_edit)
        :rtype: list
        """

        projects = super(ProjectListView, self).get_queryset(*args, **kwargs)
        user = self.request.user
        items = []
        for p in projects:
            roles = p.determine_roles(user) if user.is_authenticated() else []
            items.append((p, len(roles) > 0, ProjectRole.ROLE_PROJECT_ADMIN in roles, ProjectRole.ROLE_PROJECT_ADMIN in roles))
        return items

class ProjectDetailView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    """Detail view for the Project model"""

    model = Project
    #test_func = Project.can_detail

    def test_func(self, user):
        obj = self.get_object()
        return obj.can_detail(user)

    def dispatch(self, *args, **kwargs):
        return super(ProjectDetailView, self).dispatch(*args, **kwargs)

# TODO: Class below belongs to forms.py
class ProjectRoleInline(InlineFormSet):
    """Utility-class: ProjectRoles displayed as a InlineFormset"""

    model = ProjectRole
    extra = 2

class ProjectCreateView(LoginRequiredMixin, CreateWithInlinesView, NamedFormsetsMixin):
    """Create view for the Project model"""

    model = Project
    form_class = ProjectForm
    template_name = 'research/project_create.html'
    inlines = [ProjectRoleInline,]
    inlines_names = ['projectrole_formset', ]

    def forms_valid(self, form, inlines):
        """Saves the formsets and redirects to Project's detail page."""

        self.object = form.save(commit=False)
        self.object.save()
        projectrole_formset = inlines[0]
        projectrole_formset.save()
        return HttpResponseRedirect(self.object.get_absolute_url())

class ProjectUpdateView(UpdateWithInlinesView, NamedFormsetsMixin):
    """Create view for the Project model"""

    model = Project
    form_class = ProjectForm
    template_name = 'research/project_create.html'
    inlines = [ProjectRoleInline,]
    inlines_names = ['projectrole_formset', ]

    def forms_valid(self, form, inlines):
        """Saves the formsets and redirects to Project's detail page."""

        self.object = form.save(commit=False)
        self.object.save()
        projectrole_formset = inlines[0]
        projectrole_formset.save()
        return HttpResponseRedirect(self.object.get_absolute_url())

class ProjectDeleteView(LoginRequiredMixin, ObjectAccessRequiredMixin, generic.DeleteView):
    """Delete view of the project object.
    Given resource can be removed when user is the owner or the uploader of the resource.
    """

    model=Project
    access_func = Project.can_delete
    success_url='project/list/'
    context_object_name='object'
    template_name='research/project_confirm_delete.html'

    def dispatch(self, *args, **kwargs):
        return super(ProjectDeleteView, self).dispatch(*args, **kwargs)


class ProjectCollectionCreateView(LoginRequiredMixin, AjaxFormMixin):
    """Collection's create view.
    Handles the creation of the Collection object.
    """
    raise_exception = True
    ajax_form = ProjectCollectionForm

    @csrf_exempt
    def dispatch(self, *args, **kwargs):
        return super(ProjectCollectionCreateView, self).dispatch(*args, **kwargs)

    def json_in_data_test(self, in_data, request):
        collection = Collection.objects.get(pk=in_data['collection'])
        if not collection.can_update(self.request.user):
            raise PermissionDenied()

trapper/apps/research/templates/research/base.html
{% extends "base.html" %}

{% block master_content %}
<ul class="nav nav-pills">
	<li {% block research_project_list %}{% endblock %}><a href="{% url "research:project_list" %}">All projects</a></li>
</ul>
<div>
{% block content %}{% endblock content %}
</div>
{% endblock master_content %}

trapper/apps/research/templates/research/index.html
{% extends "research/base.html" %}

{% block content %}
Welcome to Research module!
<br />
(Intro here)
<br />
{% endblock content %}

trapper/apps/research/templates/research/project_confirm_delete.html
{% extends "storage/base.html" %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
Are you sure you want to delete "{{object.name}}" ?
<br />
<input type="submit" value="Yes" />
</form>
{% endblock content %}

trapper/apps/research/templates/research/project_create.html
{% extends "research/base.html" %}
{% load staticfiles %}
{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% block header %}
<script type="text/javascript" src="{% static "jquery.formset.js" %}"></script>
<script type="text/javascrip">
	$(function() {
		$('#collectionForm tbody tr').formset({
			prefix: '{{ collection_formset.prefix }}',
			formCssClass: 'dynamic_collection_formset'
		});
		$('#projectroleForm tbody tr').formset({
			prefix: '{{ projectrole_formset.prefix }}',
			formCssClass: 'dynamic_projectrole_formset'
		});
	});
</script>

{{form.media}}

{% endblock header %}

<form id="projectForm" class="form-horizontal" action="" method="post">
{% csrf_token %}
<div class="form-group">
	<label for="inputEmail3" class="col-sm-2 control-label">Project name:</label>
	<div class="col-sm-10">
		{{ form.name }}
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label">Project description:</label>
	<div class="col-sm-10">
		{{form.description}}
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label">Users in this project:</label>
	<div class="col-sm-10">
		{{ projectrole_formset.management_form }}
		<table id="projectroleForm" class="table">
			<thead>
				<th>Username</th>
				<th>Role</th>
			</thead>
			<tbody>
		{% for form in projectrole_formset.forms %}
			{{form.id}}
			<tr>
				<td>{{form.user}}</td>
				<td>{{form.name}}</td>
				<td>{% if form.instance.pk %}{{form.DELETE}}{% endif %}</td>
			</tr>
			</tbody>
		{% endfor %}
		</table>
	</div>
</div>

<input class="btn btn-primary" type="submit" value="Update" />
</form>

{% endblock content %}

trapper/apps/research/templates/research/project_detail.html
{% extends "research/base.html" %}
{% load staticfiles %}
{% block content %}
<h1>{{ project.name }}</h1>
<br/>

<div class="panel panel-primary">
  <div class="panel-heading">
    Project description:
  </div>
  <div class="panel-body">
    <p>
      {% if project.description %}
      {{ project.description | safe}}
      {% else %}
      This project has no description yet.
      {% endif %}
    </p>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    Researchers in this project:
  </div>
  <div class="panel-body">
    <table class="table">
      <th>User</th>
      <th>Role</th>
      {% for role in project.projectrole_set.all %}
      <tr><td>{{role.user.username}}</td><td>{{role.get_name_display}}</td></tr>
      {% endfor %}
    </table>
    <a class="btn btn-md btn-success" href="{% url "storage:resource_create" %}">Add researchers <span class="glyphicon glyphicon-user"></span></a>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    Resource collections for this project:
  </div>
  <div class="panel-body">
    <div class="panel-group" id="accordion">
      {% for pc in project.collections.all %}
      <div class="panel panel-default">
	<div class="panel-heading">
	  {{pc.name}} <a data-toggle="collapse" data-parent="#accordion" href="#collection{{pc.pk}}"><span class="glyphicon glyphicon-chevron-down"></span></a>
	</div>
	<div id="collection{{pc.pk}}" class="panel-collapse collapse out">
	  <table class="table">
	    <th>Name</th>
	    <th>Owner</th>
	    <th>Uploader</th>
	    <th>Details</th>
	    <th>Classify</th>
	    {% for resource in pc.resources.all %}
	    <tr>
	      <td>{{ resource.name }}</td>
	      <td>{{ resource.owner.username }}</td>
	      <td>{{ resource.uploader.username }}</td>
	      <td><a href="{% url "storage:resource_detail" resource.id %}" title="Details"><span class="glyphicon glyphicon-search"></span></a></td>
	      <td><a href="{% url "media_classification:classify" project.id resource.id pc.id %}" title="Classify Resource"><span class="glyphicon glyphicon-eye-open"></span></a></td>
	    </tr>
	    {% endfor %}
	  </table>
	</div>
      </div>
      {% endfor %}
    </div>  
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    Classification projects:
  </div>
  <div class="panel-body">
    <table class="table">
      <tr>
	<th>Name</th>
	<th>Crowd Sourcing</th>
	<th>Details</th>
      </tr>
      {% for cproject in project.classification_projects.all %}
      <tr>
	<td>{{ cproject.name }}</td>
	<td>{{ cproject.cs_enabled }}</td>
	<td><a href="{% url "media_classification:project_detail" cproject.id %}" title="Details"><span class="glyphicon glyphicon-search"></span></a></td>
      </tr>
      {% endfor %}
    </table>
    <a class="btn btn-md btn-success" href="{% url "media_classification:project_create" project.id %}">New classification project <span class="glyphicon glyphicon-eye-open"></span></a>
  </div>
</div>

{% endblock content %}

trapper/apps/research/templates/research/project_list.html
{% extends "research/base.html" %}
{% load staticfiles %}
{% block research_project_list %} class="active" {% endblock %}
{% block content %}
{% if items %}
Available projects:
<table class="table">
<th>Project Name</th>
<th>Project Staff</th>
<th>Details</th>
<th>Edit</th>
<th>Delete</th>
{% for project, can_view, can_edit, can_delete in items %}
<tr>
	<td>{{ project.name }}</td>
	<td>
	{% for r in project.projectrole_set.all %}
	<a href="{{r.user.userprofile.get_absolute_url}}">{{r.user}}</a>({{r.get_name_display}}),
	{% endfor %}
	</td>
	<td>
		{% if can_view %}
		<a href="{% url "research:project_detail" project.id %}"><span class="glyphicon glyphicon-search"></span></a>
		{% else %}
		<span class="glyphicon glyphicon-ban-circle"></span>
		{% endif %}
	</td>
	<td>
		{% if can_edit %}
		<a href="{% url "research:project_update" project.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
		{% else %}
		<span class="glyphicon glyphicon-ban-circle"></span>
	{% endif %}
	</td>
	<td>
		{% if can_delete %}
		<a href="{% url "research:project_delete" project.id %}"><span class="glyphicon glyphicon-remove"></span></a>
		{% else %}
		<span class="glyphicon glyphicon-ban-circle"></span>
	{% endif %}
	</td>
</tr>
{% endfor %}
</table>
{% else %}
No project available. Start one now!
{% endif %}
<p>
	<a class="btn btn-sm btn-success" href="{% url "research:project_create" %}">Create new project <span class="glyphicon glyphicon-book"></span></a>
</p>
{% endblock content %}

trapper/apps/research/templates/research/project_update.html
{% extends "media_classification/base.html" %}
{% load staticfiles %}

{# Extra header: django-dynamic-formset #}
{% block header %}
<script type="text/javascript" src="{% static "jquery.formset.js" %}"></script>
<script type="text/javascript">
	$(function() {
		$('#collectionForm tbody tr').formset({
			prefix: '{{ collection_formset.prefix }}',
			formCssClass: 'dynamic_collection_formset'
		});
		$('#projectroleForm tbody tr').formset({
			prefix: '{{ projectrole_formset.prefix }}',
			formCssClass: 'dynamic_projectrole_formset'
		});
	});
</script>
{% endblock header %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="" method="post">
{% csrf_token %}

<h2>Name: {{form.name}}</h2>
<h3>Feature sets:</h3>
{{form.feature_sets}}
<h3>CS-Enabled for this project: {{form.cs_enabled}}</h3>
<h3>Collections:</h3>
<table id="collectionForm" class="table">
	<thead>
		<th>Name</th>
		<th>Is active ?</th>
		<th>Crowd Sourcing enabled ?</th>
		<th>Delete</th>
	</thead>
	<tbody>
	{% for form in collection_formset.forms %}
		<tr id="{{form.prefix}}-row">
			{{form.id}}
			<td>{{form.col_name}}</td>
			<td>{{form.active}}</td>
			<td>{{form.cs_enabled}}</td>
			<td>{% if form.instance.pk %}{{ form.DELETE }}{% endif %}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
{{ collection_formset.management_form }}

<h3>Roles:</h3>
<table id="projectroleForm" class="table">
	<thead>
		<th>User</th>
		<th>Role</th>
		<th>Delete</th>
	</thead>
	<tbody>
	{% for form in projectrole_formset.forms %}
		 <tr id="{{form.prefix}}-row">
			{{form.id}}
			<td>{{form.user}}</td>
			<td>{{form.name}}</td>
			<td>{% if form.instance.pk %}{{form.DELETE}}{% endif %}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
{{ projectrole_formset.management_form }}

<input class="btn btn-primary" type="submit" value="Update" />
</form>

{% endblock content %}